const THEMIS_ENDPOINT_URL = process.env.THEMIS_ENDPOINT_URL ?? "https://themis.vlaanderen.be"
const THEMIS_ENDPOINT_SPARQL = `${THEMIS_ENDPOINT_URL}/sparql`;
const THEMIS_ENDPOINT_DATASETS = `${THEMIS_ENDPOINT_URL}/datasets`;

export {
  THEMIS_ENDPOINT_SPARQL,
  THEMIS_ENDPOINT_DATASETS
}
